export const responseData = {
  answers: [
    {
      id: 30,
      assessmentUserAnswerId: 15,
      assessmentQuestionId: 30,
      answer: "bibin",
      isCorrect: true,
      metadata: {
        question: "what is your name?",
      },
      userAnswer: {
        id: 15,
        assessmentId: 3,
        userId: 16,
        timeSpent: 2,
        startedAt: "2022-12-28T11:33:05.000Z",
        endedAt: "2022-12-28T11:33:07.000Z",
        metadata: {
          score: 10,
          totalMarks: 10,
          totalCorrectAnswers: 2,
        },
        user: {
          id: 16,
          firstName: "newgui",
          lastName: "new",
          email: "newgui@vma.com",
          phoneNumber: "1232112311",
          countryCode: null,
          status: "ACTIVE",
          isArchived: false,
          lastActiveAt: null,
          role: "STUDENT",
          notificationToken: null,
          deviceId: null,
          platform: null,
          appVersion: null,
          lastActiveIp: null,
          dob: null,
          language: null,
          orientation: null,
          accessibleCourses: {
            module2: "GUITAR",
          },
          guitarCalibrationData: null,
          profile_photo: null,
          attendedPreLessonTest: false,
          attendedPostLessonTest: false,
        },
      },
      question: {
        id: 30,
        question: "what is your name?",
        type: "MCQ",
        options: [
          {
            label: "jose",
            is_correct: false,
          },
          {
            label: "bibin",
            is_correct: true,
          },
          {
            label: "vijay",
            is_correct: false,
          },
        ],
        order: 1,
        assessmentId: 3,
        fileId: null,
      },
    },
    {
      id: 31,
      assessmentUserAnswerId: 15,
      assessmentQuestionId: 31,
      answer: "SAD",
      isCorrect: true,
      metadata: {
        question: "is music session good?",
      },
      userAnswer: {
        id: 15,
        assessmentId: 3,
        userId: 16,
        timeSpent: 2,
        startedAt: "2022-12-28T11:33:05.000Z",
        endedAt: "2022-12-28T11:33:07.000Z",
        metadata: {
          score: 10,
          totalMarks: 10,
          totalCorrectAnswers: 2,
        },
        user: {
          id: 16,
          firstName: "newgui",
          lastName: "new",
          email: "newgui@vma.com",
          phoneNumber: "1232112311",
          countryCode: null,
          status: "ACTIVE",
          isArchived: false,
          lastActiveAt: null,
          role: "STUDENT",
          notificationToken: null,
          deviceId: null,
          platform: null,
          appVersion: null,
          lastActiveIp: null,
          dob: null,
          language: null,
          orientation: null,
          accessibleCourses: {
            module2: "GUITAR",
          },
          guitarCalibrationData: null,
          profile_photo: null,
          attendedPreLessonTest: false,
          attendedPostLessonTest: false,
        },
      },
      question: {
        id: 31,
        question: "is music session good?",
        type: "LIKERT_SCALE",
        options: [
          {
            label: "SAD",
            emotion: "SAD",
            is_correct: true,
          },
          {
            label: "NEUTRAL",
            emotion: "NEUTRAL",
            is_correct: true,
          },
          {
            label: "HAPPY",
            emotion: "HAPPY",
            is_correct: true,
          },
          {
            label: "VERY_HAPPY",
            emotion: "VERY_HAPPY",
            is_correct: true,
          },
        ],
        order: 2,
        assessmentId: 3,
        fileId: null,
      },
    },
  ],
};
